#!/bin/bash
device="wlp2s0u5"
clear
 echo -e "

      \t         ON (   1   )  "

    echo -e "

      \t         OFF (   2   )  "

    echo -n "

                 -> Введите значение : "

      read main_menu
      case "$main_menu" in
         "1" ) clear ;
sudo systemctl stop NetworkManager
sudo ifconfig $device down
sudo iw $device set monitor control
sudo ifconfig $device up
           ;;
         "2" ) clear ;
sudo ifconfig $device down
sudo iw $device set type managed
sudo ifconfig $device up
sudo systemctl start NetworkManager
      esac
